### ISSUE TITLE
request features pipeline/prevention failed download golang file

### ISSUE THREAD

**Issue by malikshi** [skiy/golang-install#1]
can you add prevention/trying again if golang file failed to download? e.g in middle downloading the connection timeout/broken

**Comment by flydo** [comment]
https://github.com/jetsung/golang-install/blob/cd409432a6c8069eff2cf80c60c3ffdc95434360/install.sh#L247

Timeout mechanism has been added.

**Comment by malikshi** [comment]
> Timeout mechanism has been added

Thank you very much!
