### ISSUE TITLE
increase time to 2 min, 30s too short for modem speed

### ISSUE THREAD

**Issue by malikshi** [skiy/golang-install#2]
https://github.com/jetsung/golang-install/blob/c473c231315789b34db4568ad5f2d7b85de23d3f/install.sh#LL239C4-L239C37

**Comment by malikshi** [comment]
https://github.com/jetsung/golang-install/pull/3

**Comment by flydo** [comment]
Add some parameters.
```bash
curl -Lk --connect-timeout 30 --retry 5 --retry-max-time 360 --max-time 300
```

**Comment by malikshi** [comment]
Testing out in my rpi4b. Work fine. Thanks !

**Comment by ankitcharolia** [comment]
@jetsung @malikshi Kindly try out this goenv: https://github.com/ankitcharolia/goenv
